name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Firebase Key from Secret
      run: |
        echo "${{ secrets.FIREBASE_KEY_JSON }}" > serviceAccountKey.json

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: notify-kifarm  # ชื่อ Azure App Service
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
